version: '3'
services:

  votingUI:
    image: voting-ui
    environment:
      - NEXT_PUBLIC_REDIS_CONNECTION_STRING=localhost
    ports:
      - "80:3000"
    depends_on:
      - votingDB
    networks:
      - app-network
    
  votingDB:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - app-network

  worker:
    image: vote-worker
    ports: 
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - votingDB
      - resultDB

  resultUI:
    image: result-ui
    ports: 
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - worker
  
  resultDB:
    image: "postgres"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: votes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network


networks:
  app-network:
    driver: bridge