- name: Dependency Configurator
  hosts: localhost

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - curl
          - gnupg
          - lsb-release
          - wget
        state: present

    - name: Add Kubernetes APT repository key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present

    - name: Install Helm
      block:
        - name: Download Helm script
          get_url:
            url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            dest: /tmp/get-helm-3
            mode: +x

    - name: Install Helm
      command: /tmp/get-helm-3
      when: "ansible_distribution_release == 'xenial'"  # Adjust based on your Ubuntu release

        - name: Add Trivy APT repository key
      ansible.builtin.shell:
        cmd: "wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -"
        creates: /etc/apt/trivy_key_added  # Check if the key has been added to avoid unnecessary execution
      register: trivy_key_result

    - name: Add Trivy APT repository
      ansible.builtin.shell:
        cmd: "echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list"
        creates: /etc/apt/sources.list.d/trivy.list  # Check if the repository has been added to avoid unnecessary execution
      when: trivy_key_result.changed

    - name: Update APT package cache
      ansible.builtin.package:
        name: apt
        state: latest

    - name: Install Trivy
      ansible.builtin.package:
        name: trivy
        state: present
    - name: Clean up temporary files
      file:
        path: /tmp/get-helm-3
        state: absent